// @generated drizzle-zero signature:sha256:a5c93f3a866d139e3b981984c87cf9ac198d1ecc2268605749edcdad5b5128bf
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { CustomType } from "drizzle-zero";
import type * as drizzleSchema from "../../../apps/server/src/db/schema";

const achievementTable = {
    "name": "achievement",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userID": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "icon": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "description": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "done": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean
        },
        "color": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "pct": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "sort": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        }
    },
    "primaryKey": ["id"]
} as const;
const commentTable = {
    "name": "comment",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "videoID": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "video_id"
        },
        "userID": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "gradient": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "comment", "gradient">
        },
        "text": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "likes": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "createdAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const cosmeticTable = {
    "name": "cosmetic",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userID": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "rarity": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "cost": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "color": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "owned": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean
        },
        "sort": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        }
    },
    "primaryKey": ["id"]
} as const;
const followTable = {
    "name": "follow",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userID": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "creatorHandle": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "creator_handle"
        },
        "createdAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const leagueTable = {
    "name": "league",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "daysLeft": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "days_left"
        }
    },
    "primaryKey": ["id"]
} as const;
const leagueMemberTable = {
    "name": "leagueMember",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "leagueId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "league_id"
        },
        "userID": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "gradient": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "leagueMember", "gradient">
        },
        "xp": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "streak": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        }
    },
    "primaryKey": ["id"],
    "serverName": "league_member"
} as const;
const likeTable = {
    "name": "like",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userID": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "videoID": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "video_id"
        },
        "createdAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const notificationTable = {
    "name": "notification",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userID": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "kind": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as "reward" | "streak" | "xp" | "friend"
        },
        "title": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "text": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "time": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "accent": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "read": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean
        },
        "createdAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const progressTable = {
    "name": "progress",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userID": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "videoID": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "video_id"
        },
        "watchedMs": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "watched_ms"
        },
        "completed": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean
        },
        "score": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "updatedAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const userTable = {
    "name": "user",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "handle": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "isAnonymous": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean,
            "serverName": "is_anonymous"
        },
        "email": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "role": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "admin" | "curator" | "basic"
        },
        "nativeLang": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "native_lang"
        },
        "learningLang": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "learning_lang"
        },
        "learningLevel": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "learning_level"
        },
        "goals": {
            "type": "json",
            "optional": true,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "user", "goals">
        },
        "dailyTarget": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "daily_target"
        },
        "elo": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "eloGames": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "elo_games"
        },
        "level": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "levelName": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "level_name"
        },
        "xp": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "xpToday": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "xp_today"
        },
        "xpToNext": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "xp_to_next"
        },
        "gems": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "streak": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "friendshipLevel": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "friendship_level"
        },
        "wordsLearned": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "words_learned"
        },
        "league": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "leagueRank": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "league_rank"
        },
        "mascotCosmetic": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "mascot_cosmetic"
        },
        "onboarded": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean
        },
        "mergedInto": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "merged_into"
        },
        "createdAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const videoTable = {
    "name": "video",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "category": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "catEn": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "cat_en"
        },
        "creatorName": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "creator_name"
        },
        "creatorHandle": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "creator_handle"
        },
        "creatorGradient": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "video", "creatorGradient">,
            "serverName": "creator_gradient"
        },
        "creatorFollowers": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "creator_followers"
        },
        "creatorVerified": {
            "type": "boolean",
            "optional": false,
            "customType": null as unknown as boolean,
            "serverName": "creator_verified"
        },
        "creatorMascot": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean,
            "serverName": "creator_mascot"
        },
        "bgGradient": {
            "type": "json",
            "optional": false,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "video", "bgGradient">,
            "serverName": "bg_gradient"
        },
        "caption": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "likes": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "comments": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "shares": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "tag": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "subtitle": {
            "type": "json",
            "optional": false,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "video", "subtitle">
        },
        "quiz": {
            "type": "json",
            "optional": false,
            "customType": null as unknown as CustomType<typeof drizzleSchema, "video", "quiz">
        },
        "hlsUrl": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "hls_url"
        },
        "youtubeId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "youtube_id"
        },
        "langCode": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "lang_code"
        },
        "difficulty": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "createdAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const vocabularyTable = {
    "name": "vocabulary",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "userID": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "en": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "ru": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "type": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as "word" | "phrase"
        },
        "source": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "example": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "mastery": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "createdAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const achievementRelationships = {
    "user": [{ "sourceField": ["userID"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
const commentRelationships = {
    "video": [{ "sourceField": ["videoID"], "destField": ["id"], "destSchema": "video", "cardinality": "one" }],
    "user": [{ "sourceField": ["userID"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
const cosmeticRelationships = {
    "user": [{ "sourceField": ["userID"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
const likeRelationships = {
    "video": [{ "sourceField": ["videoID"], "destField": ["id"], "destSchema": "video", "cardinality": "one" }]
} as const;
const notificationRelationships = {
    "user": [{ "sourceField": ["userID"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
const progressRelationships = {
    "user": [{ "sourceField": ["userID"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }],
    "video": [{ "sourceField": ["videoID"], "destField": ["id"], "destSchema": "video", "cardinality": "one" }]
} as const;
const userRelationships = {
    "vocabulary": [{ "sourceField": ["id"], "destField": ["userID"], "destSchema": "vocabulary", "cardinality": "many" }],
    "achievements": [{ "sourceField": ["id"], "destField": ["userID"], "destSchema": "achievement", "cardinality": "many" }],
    "cosmetics": [{ "sourceField": ["id"], "destField": ["userID"], "destSchema": "cosmetic", "cardinality": "many" }],
    "notifications": [{ "sourceField": ["id"], "destField": ["userID"], "destSchema": "notification", "cardinality": "many" }],
    "progress": [{ "sourceField": ["id"], "destField": ["userID"], "destSchema": "progress", "cardinality": "many" }]
} as const;
const videoRelationships = {
    "progress": [{ "sourceField": ["id"], "destField": ["videoID"], "destSchema": "progress", "cardinality": "many" }],
    "likeRows": [{ "sourceField": ["id"], "destField": ["videoID"], "destSchema": "like", "cardinality": "many" }],
    "commentRows": [{ "sourceField": ["id"], "destField": ["videoID"], "destSchema": "comment", "cardinality": "many" }]
} as const;
const vocabularyRelationships = {
    "user": [{ "sourceField": ["userID"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
    "tables": {
        "achievement": achievementTable,
        "comment": commentTable,
        "cosmetic": cosmeticTable,
        "follow": followTable,
        "league": leagueTable,
        "leagueMember": leagueMemberTable,
        "like": likeTable,
        "notification": notificationTable,
        "progress": progressTable,
        "user": userTable,
        "video": videoTable,
        "vocabulary": vocabularyTable
    },
    "relationships": {
        "achievement": achievementRelationships,
        "comment": commentRelationships,
        "cosmetic": cosmeticRelationships,
        "like": likeRelationships,
        "notification": notificationRelationships,
        "progress": progressRelationships,
        "user": userRelationships,
        "video": videoRelationships,
        "vocabulary": vocabularyRelationships
    },
    "enableLegacyQueries": true,
    "enableLegacyMutators": false
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "achievement" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Achievement = Row<(typeof schema)["tables"]["achievement"]>;
/**
 * Represents a row from the "comment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Comment = Row<(typeof schema)["tables"]["comment"]>;
/**
 * Represents a row from the "cosmetic" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Cosmetic = Row<(typeof schema)["tables"]["cosmetic"]>;
/**
 * Represents a row from the "follow" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Follow = Row<(typeof schema)["tables"]["follow"]>;
/**
 * Represents a row from the "league" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type League = Row<(typeof schema)["tables"]["league"]>;
/**
 * Represents a row from the "leagueMember" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type LeagueMember = Row<(typeof schema)["tables"]["leagueMember"]>;
/**
 * Represents a row from the "like" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Like = Row<(typeof schema)["tables"]["like"]>;
/**
 * Represents a row from the "notification" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Notification = Row<(typeof schema)["tables"]["notification"]>;
/**
 * Represents a row from the "progress" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Progress = Row<(typeof schema)["tables"]["progress"]>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;
/**
 * Represents a row from the "video" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Video = Row<(typeof schema)["tables"]["video"]>;
/**
 * Represents a row from the "vocabulary" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Vocabulary = Row<(typeof schema)["tables"]["vocabulary"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' { interface DefaultTypes { schema: Schema; } }
