import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { asc } from "drizzle-orm";

import { db } from "@/db";
import { video } from "@/db/schema";

// Snapshot the `video` rows currently in the database into a committed seed
// file (src/db/seed-videos.gen.ts). Run this AFTER the ingestion pipeline has
// promoted real YouTube-ingested clips (rated: subtitles, quiz, ELO difficulty)
// so that `bun run db:seed` can light up a fresh dev DB with realistic feed
// data without re-running yt-dlp + the LLM stages.
//
//   bun run src/ingest/pipeline.cli.ts -- --discover   # produce `video` rows
//   bun run db:export-videos                            # snapshot -> seed-videos.gen.ts
//   bun run db:seed                                     # replay into any dev DB

const OUT = join(import.meta.dir, "seed-videos.gen.ts");

async function exportVideos() {
  const rows = await db.select().from(video).orderBy(asc(video.difficulty));
  if (rows.length === 0) {
    console.error(
      "no `video` rows to export — run the ingestion pipeline (ingest:run --discover) first.",
    );
    process.exit(1);
  }

  const header = `// GENERATED by \`bun run db:export-videos\` — do not edit by hand.
//
// Real YouTube-ingested Shorts, rated by the ingestion pipeline (RU caption,
// tokenized English subtitle with key-word translations, one comprehension
// quiz, and an ELO difficulty prior). Replayed by src/db/seed.ts so a fresh dev
// database serves a realistic feed over Zero. Regenerate after re-ingesting.
import type { video } from "@/db/schema";

export const seedVideos: (typeof video.$inferInsert)[] = ${JSON.stringify(
    rows,
    null,
    2,
  )};
`;

  writeFileSync(OUT, header);
  console.log(`✅ wrote ${rows.length} video(s) -> ${OUT}`);
  process.exit(0);
}

exportVideos().catch((err) => {
  console.error(err);
  process.exit(1);
});
